### ISSUE TITLE
VPN wird nicht wieder aufgebaut nachdem Internet Zugang weg war

### ISSUE THREAD

**Issue by Olli** [ddmesh/firmware-freifunk-dresden#3]
Ich schalte über Nacht meinen Internet-Router aus. Wenn ich ihn früh wieder anschalte, wird der Tunnel vom FF Router zu den VPN Endpunkten nicht wieder aufgebaut. 
Wenn ich das Autosetup ausführe gibt es die Meldung, dass keine Verbindung hergestellt werden kann.
Interessanterweise werden auch keine DNS Anfragen gezüglich der Entpunkte ans Internet gestellt.

**Comment by Olli** [comment]
Problem ist, dass in /tmp/resolv.conf.auto ein Nameserver, welcher durch eine statische Einstellung auf dem Laninterface da hin kam, vor dem Nameserver stand, welcher per DHCP auf dem Waninterface zugewiesen wurde.
Ich weiß nicht ob das ein Problem ist. 
Es ist vielleicht, wenn es möglich ist, interessant in der dnsmasq.conf einen "server"-Eintrag hinzuzufügen welcher für die subdomains der VPN-Endpunke explizit den DNS, welcher von WAN Seite per DHCP/statisch konfiguriert ist, nutzt.

**Comment by Olli** [comment]
Der pull ist aber nicht getestet weil ich jetzt hier kein testsystem habe

**Comment by ddmesh** [comment]
Danke, ich habe den fix gerade erst gesehen. werde ich mir mal ansehen. weiss aber noch nicht wann ich dazu komme.
